name: Monad Ethereum Tests
on:
  # run at midnight, Monday-Friday
  schedule:
    - cron: '0 0 * * 1-5'
jobs:
  build:
    strategy:
      # TODO: enable more targets and build modes
      matrix:
        CMAKE_BUILD_TYPE: [RelWithDebInfo]
        compiler: [{CXX: g++, CC: gcc}]
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}
      - name: Tune Linux Parameters
        run: |
          cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
          cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
          sudo bash -c "echo 2 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages"
          sudo bash -c "echo 1 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages"
          cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
          cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
      - name: Build docker image
        run: |
          docker build -t monad \
          --build-arg CC=${{ matrix.compiler.CC }} \
          --build-arg CXX=${{ matrix.compiler.CXX }} \
          --build-arg CMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }} \
          --build-arg DISABLE_TESTS=1 \
          --file docker/Dockerfile .
      - name: Run Ethereum tests
        run: |
          docker run --ulimit memlock=-1:-1 \
          -v ${{ github.workspace }}:/test_results/:z \
          monad \
          python3 \
          ./monad/third_party/gtest-parallel/gtest_parallel.py \
          ./monad/build/test/ethereum_test/monad-ethereum-test \
          --dump_json_test_results /test_results/results.json
      - name: Send Test Report
        if: always()
        env:
          GMAIL_APP_USER: ${{ secrets.GMAIL_APP_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          CURRENT_COMMIT: ${{ github.sha }}
        run: |
          ./scripts/ethereum-tests/send-test-coverage-report.sh
